{"name": "test_problemuser[chromium]", "status": "broken", "statusDetails": {"message": "ValueError: Unsupported type: <class 'list'>", "trace": "page = <Page url='https://www.saucedemo.com/inventory.html'>\n\n    def test_problemuser(page:Page):\n        user=\"problem_user\"\n        pswd = \"secret_sauce\"\n    \n        lp = LoginPage(page)\n    \n        lp.login(user,pswd)\n    \n        imgs = page.query_selector_all(\"div.inventory_item div a img\")\n    \n    \n>       expect(imgs).to_have_attribute(\"src\", \"/static/media/sl-404.168b1cce.jpg\")\n\ntest_loginpage.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright.sync_api.Expect object at 0x000001C637790FD0>\nactual = [<JSHandle preview=JSHandle@node>, <JSHandle preview=JSHandle@node>, <JSHandle preview=JSHandle@node>, <JSHandle preview=JSHandle@node>, <JSHandle preview=JSHandle@node>, <JSHandle preview=JSHandle@node>]\nmessage = None\n\n    def __call__(\n        self, actual: Union[Page, Locator, APIResponse], message: Optional[str] = None\n    ) -> Union[PageAssertions, LocatorAssertions, APIResponseAssertions]:\n        if isinstance(actual, Page):\n            return PageAssertions(\n                PageAssertionsImpl(actual._impl_obj, self._timeout, message=message)\n            )\n        elif isinstance(actual, Locator):\n            return LocatorAssertions(\n                LocatorAssertionsImpl(actual._impl_obj, self._timeout, message=message)\n            )\n        elif isinstance(actual, APIResponse):\n            return APIResponseAssertions(\n                APIResponseAssertionsImpl(\n                    actual._impl_obj, self._timeout, message=message\n                )\n            )\n>       raise ValueError(f\"Unsupported type: {type(actual)}\")\nE       ValueError: Unsupported type: <class 'list'>\n\nC:\\Users\\Sarath\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\sync_api\\__init__.py:142: ValueError"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1720631454343, "stop": 1720631458108, "uuid": "ade1eda8-4cb0-4d98-9513-d7680392eabe", "historyId": "90adbe24220e7968321af5fb9152a68f", "testCaseId": "968f60a40eb866030a4562dbdb69cb76", "fullName": "test_loginpage#test_problemuser", "labels": [{"name": "suite", "value": "test_loginpage"}, {"name": "host", "value": "DESKTOP-VA196IG"}, {"name": "thread", "value": "13504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_loginpage"}]}